aliases:
  - &github_config
    branch: main
    params:
      depth: 1

  - &github_app
    <<: *github_config
    uri: {{app-github-uri}}

resources:
  - name: app-source
    type: git
    source:
      <<: *github_app
      ignore_paths:
        - ci

  - name: app-ci-source
    type: git
    source:
      <<: *github_config
      paths:
        - ci

groups:
  - name: app
    jobs:
      - build-and-test

jobs:
  - name: build-and-test
    serial: true
    plan:
      - in_parallel:
          - get: app-source
            trigger: true
          - get: app-ci-source
      - task: build-and-test-app
        privileged: true
        file: app-ci-source/ci/tasks/build-and-test.yml
        params:
          MY_PARAM: {{my-param}}