pipeline-github-uri: https://github.com/mulderga-cgi/pipeline-template.git
slack-webtoken: https://hooks.slack.com/services/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
my-param: This is my param!